<?php

namespace Tests\Feature;

use App\Models\Sale;
use App\Models\User;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PDOException;
use Tests\TestCase;

/**
 * Invoice numbers are generated by reading the highest one for today and
 * adding one. Two tills doing that in the same instant compute the same
 * number, and the unique index rejects the second insert - which reached
 * production as a 500 at the point of sale.
 */
class InvoiceNumberRaceTest extends TestCase
{
    use RefreshDatabase;

    private int $userId;

    protected function setUp(): void
    {
        parent::setUp();
        $this->userId = User::factory()->create()->id;
    }

    private function saleAttributes(?string $invoiceNumber = null): array
    {
        return [
            'invoice_number' => $invoiceNumber ?? Sale::generateInvoiceNumber(),
            'wifi_code'      => Sale::generateWifiCode(),
            'user_id'        => $this->userId,
            'total_amount'   => 200,
            'status'         => 'pending',
        ];
    }

    private function makeSale(): Sale
    {
        return Sale::transactWithRetry(fn () => Sale::create($this->saleAttributes()));
    }

    private function clash(string $column): UniqueConstraintViolationException
    {
        return new UniqueConstraintViolationException(
            'mysql',
            'insert into `sales` ...',
            [],
            new PDOException("SQLSTATE[23000]: Duplicate entry 'INV-1' for key 'sales_{$column}_unique'")
        );
    }

    public function test_the_losing_till_gets_the_next_number_instead_of_a_500(): void
    {
        $first = $this->makeSale();
        $calls = 0;

        // The losing till computed the same number the winner just used.
        $second = Sale::transactWithRetry(function () use (&$calls, $first) {
            $calls++;

            return Sale::create($this->saleAttributes(
                $calls === 1 ? $first->invoice_number : null
            ));
        });

        $this->assertSame(2, $calls, 'The collision should have forced exactly one retry.');
        $this->assertNotSame($first->invoice_number, $second->invoice_number);
        $this->assertSame(2, Sale::count(), 'The rolled-back attempt must not have left a row.');
    }

    public function test_the_rolled_back_attempt_leaves_no_partial_sale(): void
    {
        $first = $this->makeSale();

        Sale::transactWithRetry(function () use ($first) {
            static $calls = 0;
            $calls++;

            $sale = Sale::create($this->saleAttributes(
                $calls === 1 ? $first->invoice_number : null
            ));

            return $sale;
        });

        // Two sales, two distinct numbers, nothing orphaned.
        $this->assertSame(2, Sale::count());
        $this->assertSame(2, Sale::distinct()->count('invoice_number'));
    }

    public function test_it_gives_up_rather_than_looping_forever(): void
    {
        $calls = 0;

        $this->expectException(UniqueConstraintViolationException::class);

        try {
            Sale::transactWithRetry(function () use (&$calls) {
                $calls++;
                throw $this->clash('invoice_number');
            }, attempts: 3);
        } finally {
            $this->assertSame(3, $calls, 'Should stop after the configured number of attempts.');
        }
    }

    public function test_an_unrelated_unique_violation_is_not_retried(): void
    {
        // Retrying a genuine duplicate would run the whole sale five times.
        $calls = 0;

        try {
            Sale::transactWithRetry(function () use (&$calls) {
                $calls++;
                throw $this->clash('customer_phone');
            });
            $this->fail('The exception should have propagated.');
        } catch (UniqueConstraintViolationException) {
            $this->assertSame(1, $calls, 'An unrelated clash must surface immediately.');
        }
    }

    public function test_a_wifi_code_collision_is_also_retried(): void
    {
        $calls = 0;

        try {
            Sale::transactWithRetry(function () use (&$calls) {
                $calls++;
                throw $this->clash('wifi_code');
            }, attempts: 2);
        } catch (UniqueConstraintViolationException) {
        }

        $this->assertSame(2, $calls);
    }

    public function test_numbers_stay_sequential_with_no_gaps(): void
    {
        // The auditor relies on an unbroken sequence.
        $suffixes = collect(range(1, 5))
            ->map(fn () => (int) substr($this->makeSale()->invoice_number, -4))
            ->all();

        $this->assertSame([1, 2, 3, 4, 5], $suffixes);
    }
}
